export const ROLES = {
  USER: "user",
  EMPLOYEE: "employee",
  ADMIN: "admin",
  SUPER_ADMIN: "superAdmin",
};

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  // users permissions

  CREATE_USER: "user:create:user",
  CREATE_EMPLOYEE: "user:create:employee",
  CREATE_ADMIN: "user:create:admin",
  CREATE_SUPER_ADMIN: "user:create:superAdmin",

  UPDATE_USER: "user:update:user",
  UPDATE_EMPLOYEE: "user:update:employee",
  UPDATE_ADMIN: "user:update:admin",
  UPDATE_SUPER_ADMIN: "user:update:superAdmin",

  DELETE_USER: "user:delete:user",
  DELETE_EMPLOYEE: "user:delete:employee",
  DELETE_ADMIN: "user:delete:admin",
  DELETE_SUPER_ADMIN: "user:delete:superAdmin",

  // products permissions

  CREATE_PRODUCT: "product:create",
  UPDATE_PRODUCT: "product:update",
  DELETE_PRODUCT: "product:delete",

  // categories permissions

  CREATE_CATEGORY: "category:create",
  UPDATE_CATEGORY: "category:update",
  DELETE_CATEGORY: "category:delete",

  // pucharse permissions

  UPDATE_PURCHASE: "purchase:update",
};

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  user: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.DELETE_USER,
  ],

  employee: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.DELETE_USER,

    PERMISSIONS.UPDATE_PURCHASE,

    PERMISSIONS.CREATE_PRODUCT,
    PERMISSIONS.UPDATE_PRODUCT,
    PERMISSIONS.DELETE_PRODUCT,

    PERMISSIONS.CREATE_CATEGORY,
    PERMISSIONS.UPDATE_CATEGORY,
    PERMISSIONS.DELETE_CATEGORY,
  ],

  admin: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.CREATE_EMPLOYEE,
    PERMISSIONS.CREATE_ADMIN,

    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.UPDATE_EMPLOYEE,
    PERMISSIONS.UPDATE_ADMIN,

    PERMISSIONS.DELETE_USER,
    PERMISSIONS.DELETE_EMPLOYEE,

    PERMISSIONS.CREATE_PRODUCT,
    PERMISSIONS.UPDATE_PRODUCT,
    PERMISSIONS.DELETE_PRODUCT,

    PERMISSIONS.CREATE_CATEGORY,
    PERMISSIONS.UPDATE_CATEGORY,
    PERMISSIONS.DELETE_CATEGORY,

    PERMISSIONS.UPDATE_PURCHASE,
  ],

  superAdmin: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.CREATE_EMPLOYEE,
    PERMISSIONS.CREATE_ADMIN,
    PERMISSIONS.CREATE_SUPER_ADMIN,

    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.UPDATE_EMPLOYEE,
    PERMISSIONS.UPDATE_ADMIN,
    PERMISSIONS.UPDATE_SUPER_ADMIN,

    PERMISSIONS.DELETE_USER,
    PERMISSIONS.DELETE_EMPLOYEE,
    PERMISSIONS.DELETE_ADMIN,
    PERMISSIONS.DELETE_SUPER_ADMIN,

    PERMISSIONS.CREATE_PRODUCT,
    PERMISSIONS.UPDATE_PRODUCT,
    PERMISSIONS.DELETE_PRODUCT,

    PERMISSIONS.CREATE_CATEGORY,
    PERMISSIONS.UPDATE_CATEGORY,
    PERMISSIONS.DELETE_CATEGORY,

    PERMISSIONS.UPDATE_PURCHASE,
  ],
};
